const Phrases = [
  "O primeiro passo não precisa ser perfeito, só precisa ser dado.",
  "Quem planta coragem colhe conquistas.",
  "O amanhã pertence a quem se prepara hoje.",
  "Fracasso é apenas um desvio, não um beco sem saída.",
  "Sua maior limitação vive apenas na sua mente.",
  "O medo é um sinal: você está no caminho certo.",
  "Pequenos hábitos constroem grandes destinos.",
  "A disciplina de hoje é a liberdade de amanhã.",
  "Você não precisa ver a escada inteira — só o próximo degrau.",
  "O não que você teme é a porta para o sim que você deseja.",
  "Todo expert já foi iniciante. Comece.",
  "O tempo não espera, mas recompensa quem o usa bem.",
  "Dificuldade é apenas oportunidade disfarçada.",
  "O corpo alcança o que a mente acredita.",
  "Sonhos sem ação são apenas desejos.",
  "A consistência vence o talento quando o talento não é consistente.",
  "Errou? Ótimo. Você está aprendendo.",
  "O sucesso não é sorte, é repetição de boas escolhas.",
  "Seu futuro é criado pelo que você faz hoje, não amanhã.",
  "A zona de conforto é um lugar bonito, mas nada cresce lá.",
  "Você é mais forte do que seus medos mais altos.",
  "O não de hoje pode virar o sim de amanhã.",
  "Grandes coisas nunca vêm de zonas de conforto.",
  "O que você faz hoje ecoa na eternidade.",
  "A dor de hoje é a força de amanhã.",
  "Você não falha quando cai — falha quando não se levanta.",
  "O segredo do sucesso? Começar antes de estar pronto.",
  "Seus limites são apenas pontos de partida.",
  "A jornada de mil milhas começa com um passo torto.",
  "O impossível é só uma opinião.",
  "Quem nunca desistiu já venceu.",
  "O ontem acabou. Hoje é o seu novo começo.",
  "Você não precisa ser grande para começar, mas precisa começar para ser grande.",
  "O medo mata mais sonhos do que o fracasso jamais matará.",
  "A vida começa onde termina sua zona de conforto.",
  "O que você acha que não pode, provavelmente pode.",
  "A persistência é o caminho dos fortes.",
  "Seu maior adversário mora no espelho — vença-o.",
  "O sucesso é alugado, e o aluguel vence todo dia.",
  "Você é o autor da sua história — escreva um best-seller.",
  "O não que você ouviu foi só um teste de coragem.",
  "A cada não, você fica mais perto do sim.",
  "O que parece o fim é apenas uma curva na estrada.",
  "Você não está atrasado — está exatamente onde precisa estar.",
  "O fracasso é um professor, não um juiz.",
  "A coragem não é ausência de medo, é ação apesar dele.",
  "O que você faz com 1% de chance define quem você é.",
  "O universo recompensa a ação, não a intenção.",
  "Você já sobreviveu a 100% dos seus piores dias.",
  "O hoje é o amanhã que você temia ontem.",
  "O que você alimenta cresce — alimente seus sonhos.",
  "A vida é curta demais para adiar o que importa.",
  "Você não precisa de permissão para brilhar.",
  "O que parece impossível hoje será seu aquecimento amanhã.",
  "A dúvida mata mais sonhos do que o fracasso.",
  "Você é a média das 5 escolhas que faz hoje.",
  "O sucesso não é para quem quer — é para quem faz.",
  "O que você resiste, persiste. O que você enfrenta, desaparece.",
  "Seu potencial é ilimitado — suas desculpas não.",
  "A vida não melhora por acaso, melhora por mudança.",
  "O maior risco é não arriscar nada.",
  "Você não falhou — sua estratégia só precisa de ajustes.",
  "O que você faz quando ninguém vê define quem você é.",
  "A paciência é amarga, mas seu fruto é doce.",
  "O que você busca está buscando você — vá ao encontro.",
  "Você não está perdido, está explorando novos caminhos.",
  "O esforço de hoje é o troféu de amanhã.",
  "A vida é um rascunho — reescreva até ficar perfeita.",
  "O que parece um obstáculo é apenas um degrau disfarçado.",
  "Você já é suficiente — agora prove para si mesmo.",
  "O silêncio dos invejosos é seu maior aplauso.",
  "O que você faz com o hoje molda o seu amanhã.",
  "A coragem é um músculo — quanto mais usa, mais forte fica.",
  "O fracasso é um evento, não uma pessoa.",
  "Você não precisa ser perfeito, precisa ser persistente.",
  "O que você planta com suor, colhe com orgulho.",
  "A vida é 10% o que acontece e 90% como você reage.",
  "O seu melhor ainda está por vir — continue.",
  "O que você teme fazer é o que mais precisa fazer.",
  "A jornada vale mais que o destino.",
  "Você não está cansado, está prestes a vencer.",
  "O que parece o fim é apenas o começo disfarçado.",
  "A persistência transforma pedras em pontes.",
  "Você é mais capaz do que jamais imaginou.",
  "O hoje é o único dia que você pode mudar.",
  "O que você faz em silêncio grita nos resultados.",
  "A vida recompensa quem não desiste no meio do caminho.",
  "Você não precisa ver o topo da montanha para subir.",
  "O que você faz hoje pode melhorar todos os seus amanhãs.",
  "A coragem é o primeiro passo para a grandeza.",
  "Você já venceu batalhas que nem lembra — continue lutando.",
  "O que parece impossível é só uma questão de perspectiva.",
  "A vida é curta demais para viver o sonho de outra pessoa.",
  "Você é o arquiteto do seu destino — construa com ousadia.",
  "A persistência é o superpoder dos comuns que vencem.",
  "Você não falhou — apenas descobriu 99 formas que não funcionam.",
  "O amanhã pertence a quem acredita no hoje.",
  "Você é mais forte do que ontem — e amanhã será ainda mais.",
  "Você é capaz de transformar desafios em conquistas.",
  "Você é o arquiteto do seu próprio destino.",
  "Você é mais forte do que qualquer obstáculo no seu caminho.",
  "Você é merecedor de tudo que deseja realizar.",
  "Você é a mudança que quer ver no mundo.",
  "Você é resiliente, e cada queda o levanta mais alto.",
  "Você é criador de possibilidades, não vítima de circunstâncias.",
  "Você é luz em meio à escuridão que tenta atravessar.",
  "Você é disciplina em movimento, não apenas intenção.",
  "Você é o protagonista da sua história, não mero espectador.",
  "Você é coragem disfarçada de ação diária.",
  "Você é aprendizado constante, nunca um fracasso final.",
  "Você é energia que atrai o que foca e cultiva.",
  "Você é paz interior, mesmo em meio à tempestade.",
  "Você é o sim que dá a si mesmo todos os dias.",
];

export default Phrases;
