const Phrases = [
  "O primeiro passo não precisa ser perfeito, só precisa ser dado.",
  "Quem planta coragem colhe conquistas.",
  "O amanhã pertence a quem se prepara hoje.",
  "Fracasso é apenas um desvio, não um beco sem saída.",
  "Sua maior limitação vive apenas na sua mente.",
  "O medo é um sinal: você está no caminho certo.",
  "Pequenos hábitos constroem grandes destinos.",
  "A disciplina de hoje é a liberdade de amanhã.",
  "Você não precisa ver a escada inteira — só o próximo degrau.",
  "O não que você teme é a porta para o sim que você deseja.",
  "Todo expert já foi iniciante. Comece.",
  "O tempo não espera, mas recompensa quem o usa bem.",
  "Dificuldade é apenas oportunidade disfarçada.",
  "O corpo alcança o que a mente acredita.",
  "Sonhos sem ação são apenas desejos.",
  "A consistência vence o talento quando o talento não é consistente.",
  "Errou? Ótimo. Você está aprendendo.",
  "O sucesso não é sorte, é repetição de boas escolhas.",
  "Seu futuro é criado pelo que você faz hoje, não amanhã.",
  "A zona de conforto é um lugar bonito, mas nada cresce lá.",
  "Você é mais forte do que seus medos mais altos.",
  "O não de hoje pode virar o sim de amanhã.",
  "Grandes coisas nunca vêm de zonas de conforto.",
  "O que você faz hoje ecoa na eternidade.",
  "A dor de hoje é a força de amanhã.",
  "Você não falha quando cai — falha quando não se levanta.",
  "O segredo do sucesso? Começar antes de estar pronto.",
  "Seus limites são apenas pontos de partida.",
  "A jornada de mil milhas começa com um passo torto.",
  "O impossível é só uma opinião.",
  "Quem nunca desistiu já venceu.",
  "O ontem acabou. Hoje é o seu novo começo.",
  "Você não precisa ser grande para começar, mas precisa começar para ser grande.",
  "O medo mata mais sonhos do que o fracasso jamais matará.",
  "A vida começa onde termina sua zona de conforto.",
  "O que você acha que não pode, provavelmente pode.",
  "A persistência é o caminho dos fortes.",
  "Seu maior adversário mora no espelho — vença-o.",
  "O sucesso é alugado, e o aluguel vence todo dia.",
  "Você é o autor da sua história — escreva um best-seller.",
  "O não que você ouviu foi só um teste de coragem.",
  "A cada não, você fica mais perto do sim.",
  "O que parece o fim é apenas uma curva na estrada.",
  "Você não está atrasado — está exatamente onde precisa estar.",
  "O fracasso é um professor, não um juiz.",
  "A coragem não é ausência de medo, é ação apesar dele.",
  "O que você faz com 1% de chance define quem você é.",
  "O universo recompensa a ação, não a intenção.",
  "Você já sobreviveu a 100% dos seus piores dias.",
  "O hoje é o amanhã que você temia ontem.",
  "O que você alimenta cresce — alimente seus sonhos.",
  "A vida é curta demais para adiar o que importa.",
  "Você não precisa de permissão para brilhar.",
  "O que parece impossível hoje será seu aquecimento amanhã.",
  "A dúvida mata mais sonhos do que o fracasso.",
  "Você é a média das 5 escolhas que faz hoje.",
  "O sucesso não é para quem quer — é para quem faz.",
  "O que você resiste, persiste. O que você enfrenta, desaparece.",
  "Seu potencial é ilimitado — suas desculpas não.",
  "A vida não melhora por acaso, melhora por mudança.",
  "O maior risco é não arriscar nada.",
  "Você não falhou — sua estratégia só precisa de ajustes.",
  "O que você faz quando ninguém vê define quem você é.",
  "A paciência é amarga, mas seu fruto é doce.",
  "O que você busca está buscando você — vá ao encontro.",
  "Você não está perdido, está explorando novos caminhos.",
  "O esforço de hoje é o troféu de amanhã.",
  "A vida é um rascunho — reescreva até ficar perfeita.",
  "O que parece um obstáculo é apenas um degrau disfarçado.",
  "Você já é suficiente — agora prove para si mesmo.",
  "O silêncio dos invejosos é seu maior aplauso.",
  "O que você faz com o hoje molda o seu amanhã.",
  "A coragem é um músculo — quanto mais usa, mais forte fica.",
  "O fracasso é um evento, não uma pessoa.",
  "Você não precisa ser perfeito, precisa ser persistente.",
  "O que você planta com suor, colhe com orgulho.",
  "A vida é 10% o que acontece e 90% como você reage.",
  "O seu melhor ainda está por vir — continue.",
  "O que você teme fazer é o que mais precisa fazer.",
  "A jornada vale mais que o destino.",
  "Você não está cansado, está prestes a vencer.",
  "O que parece o fim é apenas o começo disfarçado.",
  "A persistência transforma pedras em pontes.",
  "Você é mais capaz do que jamais imaginou.",
  "O hoje é o único dia que você pode mudar.",
  "O que você faz em silêncio grita nos resultados.",
  "A vida recompensa quem não desiste no meio do caminho.",
  "Você não precisa ver o topo da montanha para subir.",
  "O que você faz hoje pode melhorar todos os seus amanhãs.",
  "A coragem é o primeiro passo para a grandeza.",
  "Você já venceu batalhas que nem lembra — continue lutando.",
  "O que parece impossível é só uma questão de perspectiva.",
  "A vida é curta demais para viver o sonho de outra pessoa.",
  "Você é o arquiteto do seu destino — construa com ousadia.",
  "A persistência é o superpoder dos comuns que vencem.",
  "Você não falhou — apenas descobriu 99 formas que não funcionam.",
  "O amanhã pertence a quem acredita no hoje.",
  "O começo é sempre bagunçado; a perfeição vem depois.",
  "Seu maior competidor é a versão de ontem de você.",
  "O 'não' dos outros nunca cancela o 'sim' que você dá a si mesmo.",
  "Quem tem medo de cair nunca aprende a voar alto.",
  "O sucesso não escolhe os talentosos, escolhe os obstinados.",
  "A cada passo fora da zona de conforto, um novo você nasce.",
  "O tempo voa, mas você pode ser o piloto.",
  "A dor que você evita hoje será a conta que pagará amanhã.",
  "O universo conspira a favor de quem não desiste.",
  "Você não precisa de mais força, precisa de mais começo.",
  "O medo é só um convidado barulhento — não precisa mandar a casa.",
  "O silêncio antes da vitória é o som da disciplina trabalhando.",
  "Quem espera o momento perfeito nunca sai do lugar.",
  "Suas cicatrizes são mapas que provam que você sobreviveu.",
  "O fracasso não te define, a sua volta sim.",
  "A vida não te dá o que você quer, te dá o que você luta.",
  "O 'quase' de hoje é o combustível do 'consegui' de amanhã.",
  "Você é mais corajoso do que acredita e mais forte do que parece.",
  "O não que você dá ao medo é o sim que você dá ao sonho.",
  "O sucesso é a soma de pequenos esforços repetidos sem parar.",
  "A dúvida é um ladrão — não deixe ela entrar em casa.",
  "Quem muda de direção no meio da tempestade chega mais rápido ao sol.",
  "O seu futuro agradece cada vez que você escolhe não desistir.",
  "O que te assusta hoje será sua maior história amanhã.",
  "A disciplina é escolher entre o que você quer agora e o que você mais quer.",
  "Você não está começando do zero, está começando do aprendizado.",
  "O maior erro é achar que o tempo vai resolver por você.",
  "A vida é um jogo: quem para de jogar perde por WO.",
  "O medo sempre fala alto, mas nunca tem razão.",
  "Você já passou por 100% dos dias ruins até hoje — esse não será diferente.",
  "O 'eu não consigo' morre no primeiro passo que você dá.",
  "O sucesso gosta de quem chega antes do horário.",
  "A preguiça cobra juros altos; a ação paga em liberdade.",
  "Você não precisa carregar o peso do mundo, só o próximo passo.",
  "O que você chama de obstáculo, o destino chama de treino.",
  "A vida inteira é um teste — a coragem é a única nota que importa.",
  "Quem corre do esforço nunca chega na linha de chegada.",
  "O seu corpo cansa, mas a sua vontade renova.",
  "O 'não sei' de hoje vira 'me ensina' de quem vence amanhã.",
  "A cada dia que você não desiste, o sonho fica mais perto.",
  "O ontem te ensinou, o hoje te transforma, o amanhã te espera.",
  "Você não falhou enquanto ainda tiver fôlego para tentar de novo.",
  "O sucesso é tímido — ele só aparece para quem insiste em chamar.",
  "A zona de conforto é o cemitério dos sonhos vivos.",
  "O que você faz quando ninguém aplaude é o que te leva ao palco.",
  "A persistência é o grito silencioso dos que vão vencer.",
  "Você não precisa de mais talento, precisa de mais tentativas.",
  "O medo é um mentiroso profissional — pare de acreditar nele.",
  "A vida é curta demais para esperar o ânimo chegar.",
  "O seu maior troféu será olhar para trás e ver o quanto lutou.",
  "Quem transforma pedras no caminho em degraus chega mais alto.",
  "O fracasso é só um recibo de que você tentou pagar o preço.",
  "A coragem não ruge sempre — às vezes é só a voz que diz 'tenta amanhã'.",
  "O que você chama de fim, os vencedores chamam de intervalo.",
  "Você é o herói da sua própria saga — aja como tal.",
  "O talento abre a porta, o esforço te mantém dentro do jogo.",
  "A vida recompensa quem troca desculpas por soluções.",
  "O seu limite de ontem é o aquecimento de hoje.",
  "Quem planta consistência colhe resultados inevitáveis.",
  "O não que você teme ouvir é só o sim disfarçado de lição.",
  "Você não está quebrado, está sendo reconstruído mais forte.",
  "O sucesso é um esporte individual disputado dentro da sua mente.",
  "A cada 'eu não mereço' que você cala, um sonho agradece.",
  "O que parece distante hoje será sua rotina amanhã.",
  "Você não precisa mover montanhas — só dar o próximo passo.",
  "O fracasso é um professor mal-humorado, mas ensina pra caramba.",
  "A vida começa de novo toda vez que você decide recomeçar.",
  "O seu potencial está esperando você parar de duvidar dele.",
  "Quem tem medo do ridículo nunca chega ao extraordinário.",
  "O hoje é o único dia em que você pode mudar a pontuação do jogo.",
  "A disciplina pesa gramas, o arrependimento pesa toneladas.",
  "Você já é vencedor só por continuar depois de cada queda.",
  "O que te derrubou ontem te ensinou a ficar de pé hoje.",
  "A coragem é o único idioma que o destino entende perfeitamente.",
  "O sucesso não tem atalhos, mas tem trilhas feitas por quem insistiu.",
  "Você não está atrasado, está sendo preparado para algo grande.",
  "O que você chama de caos, o universo chama de preparação.",
  "A cada vez que você escolhe continuar, o impossível recua um passo.",
  "O seu futuro está torcendo pelo seu presente.",
  "Quem transforma lágrimas em combustível chega mais longe.",
  "O medo é só um sinal de que algo importante está do outro lado.",
  "Você não precisa ser o melhor, precisa ser o que não desiste.",
  "A vida é uma escada rolante ao contrário — pare e ela te leva para baixo.",
  "O que você faz nos dias ruins define quem chega nos dias bons.",
  "O seu maior poder é decidir recomeçar quantas vezes forem precisas.",
  "A vitória sorri para quem chega suado, não para quem chega perfeito.",
  "O amanhã é construído com os 'hoje' que você não pulou.",
  "Você é mais forte do que qualquer motivo que inventou para parar.",
  "O sucesso é só o fracasso que continuou andando.",
  "A cada passo que você dá com medo, o medo fica menor.",
  "O que parece o fundo do poço pode ser o alicerce do castelo.",
  "Você não precisa de mais tempo, precisa de mais decisão.",
  "O destino ama quem troca 'se' por 'quando'.",
  "A vida é muito curta para deixar o medo dirigir o volante.",
  "O seu sonho não desiste de você — não desista dele.",
  "O que você acha que é o fim, na verdade é o começo com outra roupa.",
  "Você já venceu o dia que decidiu não desistir dele.",
  "A persistência é o superpoder que todo mundo tem, mas poucos usam.",
  "O universo move montanhas para quem move o primeiro tijolo.",
  "Você é a resposta que o seu futuro está esperando.",
  "Você é mais forte do que ontem — e amanhã será ainda mais.",
  "Você é capaz de transformar desafios em conquistas.",
  "Você é o arquiteto do seu próprio destino.",
  "Você é mais forte do que qualquer obstáculo no seu caminho.",
  "Você é merecedor de tudo que deseja realizar.",
  "Você é a mudança que quer ver no mundo.",
  "Você é resiliente, e cada queda o levanta mais alto.",
  "Você é criador de possibilidades, não vítima de circunstâncias.",
  "Você é luz em meio à escuridão que tenta atravessar.",
  "Você é disciplina em movimento, não apenas intenção.",
  "Você é o protagonista da sua história, não mero espectador.",
  "Você é coragem disfarçada de ação diária.",
  "Você é aprendizado constante, nunca um fracasso final.",
  "Você é energia que atrai o que foca e cultiva.",
  "Você é paz interior, mesmo em meio à tempestade.",
  "Você é o sim que dá a si mesmo todos os dias.",
  "Você é prova viva de que o impossível se curva diante da fé.",
  "Você é o milagre que estava esperando por si mesmo.",
  "Você é invencível quando decide não se abandonar.",
  "Você é o fogo que não apaga nem com o vento mais forte.",
  "Você é a força que nasce exatamente onde o medo termina.",
  "Você é o motivo pelo qual o amanhã ainda acredita em esperança.",
  "Você é mais poderoso do que qualquer tempestade que já enfrentou.",
  "Você é a própria prova de que o recomeço sempre vence.",
  "Você é o guerreiro que o seu eu criança sempre acreditou que seria.",
  "Você é o sonho de Deus caminhando com seus próprios pés.",
  "Você é o coração que insiste em bater mesmo quando tudo diz pra parar.",
  "Você é a vitória que o universo guardou só para quem não desistiu.",
  "Você é o tipo de pessoa que faz o destino mudar de ideia.",
  "Você é o abraço que o seu futuro está esperando ansiosamente.",
  "Você é a obra-prima que ainda está sendo esculpida pela coragem.",
  "Você é o herói que o mundo nem sabia que precisava.",
  "Você é o motivo pelo qual o impossível aprendeu a ter medo.",
  "Você é a luz que nasceu para iluminar até os próprios dias escuros.",
  "Você é o grito de liberdade que ecoa dentro do seu peito.",
  "Você é o amor que nunca desiste de si mesmo.",
  "Você é o milagre diário que acontece toda vez que escolhe continuar.",
  "Você é o gigante que estava dormindo dentro de um corpo comum.",
  "Você é a história que ainda fará lágrimas virarem aplausos.",
  "Você é o sim que o universo precisava ouvir para conspirar a seu favor.",
  "Você é o motivo pelo qual o amanhã acorda sorrindo.",
  "Você é a força que transforma cicatrizes em estrelas.",
  "Você é o alguém que o seu eu do futuro olha com orgulho e gratidão.",
  "Você é o fenômeno que acontece quando a fé encontra coragem.",
  "Você é o legado vivo de todas as vezes que escolheu se levantar.",
  "Você é o sol que nasce mesmo depois da noite mais longa.",
  "Você é o motivo pelo qual o medo aprendeu a perder.",
  "Você é o tudo que sempre precisou ser — e está só começando.",
  "Você é eterno enquanto acreditar no próximo passo.",
  "Você é o maior ato de coragem que o universo já assistiu.",
  "Você é o amor próprio em forma de gente.",
  "Você é o final feliz que começou a ser escrito hoje.",
  "Você é mais forte do que ontem — e amanhã será ainda mais.",
  "Você é capaz de transformar desafios em conquistas.",
  "Você é o arquiteto do seu próprio destino.",
  "Você é mais forte do que qualquer obstáculo no seu caminho.",
  "Você é merecedor de tudo que deseja realizar.",
  "Você é a mudança que quer ver no mundo.",
  "Você é resiliente, e cada queda o levanta mais alto.",
  "Você é criador de possibilidades, não vítima de circunstâncias.",
  "Você é luz em meio à escuridão que tenta atravessar.",
  "Você é disciplina em movimento, não apenas intenção.",
  "Você é o protagonista da sua história, não mero espectador.",
  "Você é coragem disfarçada de ação diária.",
  "Você é aprendizado constante, nunca um fracasso final.",
  "Você é energia que atrai o que foca e cultiva.",
  "Você é paz interior, mesmo em meio à tempestade.",
  "Você é o sim que dá a si mesmo todos os dias.",
];

export default Phrases;
